services:
  lr-fulltext-books-node:
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./config.json:/usr/src/app/config.json
    depends_on:
      es:
        condition: service_started
  es:
    image: bitnami/elasticsearch:latest
    ports:
      - 9200:9200
    volumes:
      - ~/lr-es-data:/bitnami/elasticsearch/data
